name: tacostream
description: Riding the DT

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.4.4+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  build_runner: ^1.11.0
  clippy_flutter: ^1.1.1
  cupertino_icons: ^0.1.3
  device_info: ^1.0.0
  draw: ^0.9.1
  equatable: ^1.2.5
  flutter_markdown: ^0.5.0
  flutter_spinkit: ^4.1.2+1
  flutter_web_auth: ^0.2.4
  font_awesome_flutter: ^8.10.0
  get_it: ^5.0.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  hive_generator: ^0.8.2
  html_unescape: ^1.0.2
  intl: ^0.16.1
  logger: ^0.9.4
  package_info: ^0.4.3+2
  provider: ^4.3.2+2
  rxdart: ^0.25.0
  url_launcher: ^5.7.10
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
